import pytest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import os

@pytest.fixture(scope="function")
def driver():
    # Настройка опций Chrome
    chrome_options = Options()
    
    # Определяем, запущено ли в CI (GitHub Actions)
    is_ci = os.getenv('CI') == 'true'
    
    if is_ci:
        # Настройки для GitHub Actions
        chrome_options.add_argument("--headless=new")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--disable-gpu")
        chrome_options.add_argument("--window-size=1920,1080")
        
        # Используем системный ChromeDriver в CI
        service = Service(executable_path="/usr/local/bin/chromedriver")
    else:
        # Настройки для локального запуска
        from webdriver_manager.chrome import ChromeDriverManager
        service = Service(executable_path=ChromeDriverManager().install())
    
    driver = webdriver.Chrome(service=service, options=chrome_options)
    driver.maximize_window()

    yield driver

    # Закрытие драйвера после теста
    driver.quit()
